import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateWalletEntity1758580630709 implements MigrationInterface {
    name = 'UpdateWalletEntity1758580630709'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" DROP CONSTRAINT "FK_9f7378fad687bad52b8105d81ce"`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" DROP CONSTRAINT "FK_ab5c38e6bf657be3517b355cf2a"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" DROP CONSTRAINT "FK_638983f3e5c1439e6ed4a53fba6"`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" DROP CONSTRAINT "FK_df71d0f9058318ebc25302aa365"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_sessions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_sessions_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_sessions_expires"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tokens_symbol_network"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tokens_network"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transaction_fees_transaction"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_wallet_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_tx_hash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallets_address_network"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_balances_wallet_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_network_settings_name"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "wallet_id" character varying(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "UQ_c1cf06e248522005c350032ee3b" UNIQUE ("wallet_id")`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "encrypted_private_key" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "tokens" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" ADD CONSTRAINT "UQ_9f7378fad687bad52b8105d81ce" UNIQUE ("transaction_id")`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "wallet_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ADD "wallet_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ALTER COLUMN "last_updated" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "network_settings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_559d8b45161140566f3563371a" ON "tokens" ("symbol", "network") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9f7378fad687bad52b8105d81c" ON "transaction_fees" ("transaction_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c1cf06e248522005c350032ee3" ON "wallets" ("wallet_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6e58c13f34560f7164c4750b0b" ON "wallets" ("address", "network") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e6a18fe588b3b5b8964c155a96" ON "wallet_balances" ("wallet_id", "token_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_80aec3316994e0e483d0a503ea" ON "network_settings" ("network_name") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" ADD CONSTRAINT "FK_9f7378fad687bad52b8105d81ce" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" ADD CONSTRAINT "FK_ab5c38e6bf657be3517b355cf2a" FOREIGN KEY ("fee_token_id") REFERENCES "tokens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ADD CONSTRAINT "FK_df71d0f9058318ebc25302aa365" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ADD CONSTRAINT "FK_638983f3e5c1439e6ed4a53fba6" FOREIGN KEY ("token_id") REFERENCES "tokens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wallet_balances" DROP CONSTRAINT "FK_638983f3e5c1439e6ed4a53fba6"`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" DROP CONSTRAINT "FK_df71d0f9058318ebc25302aa365"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e"`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" DROP CONSTRAINT "FK_ab5c38e6bf657be3517b355cf2a"`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" DROP CONSTRAINT "FK_9f7378fad687bad52b8105d81ce"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80aec3316994e0e483d0a503ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6a18fe588b3b5b8964c155a96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e58c13f34560f7164c4750b0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1cf06e248522005c350032ee3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f7378fad687bad52b8105d81c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_559d8b45161140566f3563371a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "network_settings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ALTER COLUMN "last_updated" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ADD "wallet_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "wallet_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" DROP CONSTRAINT "UQ_9f7378fad687bad52b8105d81ce"`);
        await queryRunner.query(`ALTER TABLE "tokens" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "encrypted_private_key"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "UQ_c1cf06e248522005c350032ee3b"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_network_settings_name" ON "network_settings" ("network_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_wallet_balances_wallet_token" ON "wallet_balances" ("token_id", "wallet_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_wallets_address_network" ON "wallets" ("address", "network") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_tx_hash" ON "transactions" ("tx_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_status" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_wallet_id" ON "transactions" ("wallet_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_transaction_fees_transaction" ON "transaction_fees" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tokens_network" ON "tokens" ("network") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_tokens_symbol_network" ON "tokens" ("network", "symbol") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_sessions_expires" ON "user_sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_sessions_token" ON "user_sessions" ("session_token") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_sessions_user_id" ON "user_sessions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_created_at" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_user_id" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ADD CONSTRAINT "FK_df71d0f9058318ebc25302aa365" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_balances" ADD CONSTRAINT "FK_638983f3e5c1439e6ed4a53fba6" FOREIGN KEY ("token_id") REFERENCES "tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_0b171330be0cb621f8d73b87a9e" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" ADD CONSTRAINT "FK_ab5c38e6bf657be3517b355cf2a" FOREIGN KEY ("fee_token_id") REFERENCES "tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_fees" ADD CONSTRAINT "FK_9f7378fad687bad52b8105d81ce" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
